# Generated by Django 4.1 on 2022-09-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_livro_autores"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
    ]
