# Generated by Django 4.1.3 on 2022-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_livro_autores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={},
        ),
        migrations.RemoveField(
            model_name="livro",
            name="autores",
        ),
    ]
